package com.kainakamura.problem002;

/**
 * Each new term in the Fibonacci sequence is generated by adding the
 * previous two terms.By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not
 * exceed four million, find the sum of the even-valued terms.
 */
public class Problem2 {
    protected static int evenFibonacciNumbers(int limit) {
        int sum = 0;
        int previousNumber = 1;
        int currentNumber = 1;

        // While not exceeding limit
        while (currentNumber <= limit) {
            // Add to sum if even number
            if (currentNumber % 2 == 0) {
                sum += currentNumber;
            }

            // Update current number and previous number
            int temp = currentNumber;
            currentNumber = currentNumber + previousNumber;
            previousNumber = temp;
        }

        return sum;
    }

    public static void main(String[] args) {
        System.out.println(evenFibonacciNumbers(4000000));
    }
}
